name: timetable_maker_app
description: "Automated clash-free university timetable maker."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  csv: ^6.0.0
  google_fonts: ^6.2.1
  excel: ^4.0.6
  file_saver: ^0.3.1
  spreadsheet_decoder: ^2.3.0
  window_manager: ^0.5.1
  file_picker: ^11.0.2
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
