// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB28azGUDX-RMdjUBe9EXBtykRDlE_WEIk',
    appId: '1:124116507988:web:f39292708b8bd6eecebcc1',
    messagingSenderId: '124116507988',
    projectId: 'timetable-manager-22211',
    authDomain: 'timetable-manager-22211.firebaseapp.com',
    storageBucket: 'timetable-manager-22211.firebasestorage.app',
    measurementId: 'G-BZPB49QXBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwk1HqiFulA3J2k0947_RADyliwSm-9iM',
    appId: '1:124116507988:android:700d7a8566be2557cebcc1',
    messagingSenderId: '124116507988',
    projectId: 'timetable-manager-22211',
    storageBucket: 'timetable-manager-22211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG-26witM3VBn2JhZ5a2iiTLdLufA7rwc',
    appId: '1:124116507988:ios:cd2abeddcd73f0f2cebcc1',
    messagingSenderId: '124116507988',
    projectId: 'timetable-manager-22211',
    storageBucket: 'timetable-manager-22211.firebasestorage.app',
    iosBundleId: 'com.example.timetableMakerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG-26witM3VBn2JhZ5a2iiTLdLufA7rwc',
    appId: '1:124116507988:ios:cd2abeddcd73f0f2cebcc1',
    messagingSenderId: '124116507988',
    projectId: 'timetable-manager-22211',
    storageBucket: 'timetable-manager-22211.firebasestorage.app',
    iosBundleId: 'com.example.timetableMakerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB28azGUDX-RMdjUBe9EXBtykRDlE_WEIk',
    appId: '1:124116507988:web:8e19577f1723f451cebcc1',
    messagingSenderId: '124116507988',
    projectId: 'timetable-manager-22211',
    authDomain: 'timetable-manager-22211.firebaseapp.com',
    storageBucket: 'timetable-manager-22211.firebasestorage.app',
    measurementId: 'G-BDDPQBT9DY',
  );
}
